### ISSUE TITLE
Non X-ray structures slowdown the preprocessing step

### ISSUE THREAD

**Issue by rgayatri** [DeepRank/DeepRank_Mut#11]
Preprocessing step stagnates with structures that are solved using NMR/cryo-EM etc. 

```
ValueError: too many values to unpack (expected 9)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/deeprank/deeprank/generate/DataGenerator.py", line 1466, in _compute_features
    feat_module.__compute_feature__(pdb_data, featgrp, featgrp_raw, variant)
  File "/deeprank/deeprank/features/accessibility.py", line 42, in __compute_feature__
    for atom in get_atoms_of_iterest(variant, distance_cutoff):
  File "/deeprank/deeprank/features/accessibility.py", line 17, in get_atoms_of_iterest
    for atom1, atom2 in get_residue_contact_atom_pairs(pdb,
  File "/deeprank/deeprank/operate/pdb.py", line 74, in get_residue_contact_atom_pairs
    atoms = get_atoms(pdb2sql)
  File "/deeprank/deeprank/operate/pdb.py", line 37, in get_atoms
    raise ValueError("Got unexpected row {} for {}".format(row, request_s))
```
This error is followed by:
![Screenshot from 2021-11-11 15-20-12](https://user-images.githubusercontent.com/7666442/141451610-49d62614-57e4-483b-b19f-ab22c2984797.png)

**Comment by rgayatri** [comment]
Two pull requests started to solve the above issue:

- fix for atoms that are not in the forcefield 
https://github.com/DeepRank/DeepRank_Mut/pull/8 

- Adaptation to use X-ray structures only 
https://github.com/DeepRank/DeepRank_Mut/pull/9
